timezone: Europe/Rome
url: https://emymin.github.io

defaults:
  -
    scope:
      path: ""
    values:
      thumbnail: "/assets/images/lily.png"
  -
    scope:
      path: "collections/_posts"
    values:
      hide_title: true
  -
    scope:
      path: "creations/renders/images"
    values:
      render: true
  -
    scope:
      path: "vr/screenshots/vrc"
    values:
      vrc_screenshot: true
  -
    scope:
      path: "vr/screenshots/neos"
    values:
      neos_screenshot: true
  -
    scope:
      path: "misc/minecraft/images"
    values:
      minecraft_build: true

collections_dir: collections
collections:
  posts:
    permalink: /blog/:year/:month/:day/:title