timezone: Europe/Rome
url: https://emymin.github.io

defaults:
  -
    scope:
      path: ""
    values:
      thumbnail: "/assets/images/lily.png"
  -
    scope:
      path: "_posts"
    values:
      hide_title: true


collections:
  posts:
    permalink: /blog/:year/:month/:day/:title